server:
  port: 4550
  shutdown: "graceful"

# If you use a database then uncomment the `group:, readiness: and include: "db"` lines in the health probes and uncomment the datasource section
management:
  endpoint:
    health:
      show-details: "never"
  endpoints:
    web:
      base-path: /
      exposure:
        include: health, info, prometheus

springdoc:
  writer-with-order-by-keys: true

spring:
  servlet:
    multipart:
      max-file-size: 5MB
  http:
    converters:
      preferred-json-mapper: true
  # Continue to use Jackson 2 for now
  jackson:
    use-jackson2-defaults: true
    deserialization:
      fail-on-unknown-properties: true
  data:
    web:
      pageable:
        one-indexed-parameters: false
        # The page name parameters do not make any difference as they are
        # hard coded into the open api spec
        page-parameter: page
        size-parameter: pageSize
        default-page-size: 10
        max-page-size: 100
      sort:
        sort-parameter: sort
  config:
    import: "optional:configtree:/mnt/secrets/appreg/"
  application:
    name: Application Registration API
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DATABASE:appreg-db}?reWriteBatchedInserts=true
    username: ${POSTGRES_USER:app_reg_user}
    password: ${POSTGRES_PASS:password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        default_schema: ${spring.sql.init.schema-locations}
        default_batch_fetch_size: 25
        jdbc:
          time_zone: UTC
          batch_size: 25
        order_inserts: true
        order_updates: true
  flyway:
    enabled: ${ENABLE_DB_MIGRATE:false}
    locations: classpath:/migrations
    default-schema: ${spring.sql.init.schema-locations}
    mixed: true
  sql:
    init:
      mode: never
      schema-locations: ${APP_REG_SCHEMA:appreg}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AZURE_ISSUER:https://login.microsoftonline.com/${spring.security.oauth2.resourceserver.jwt.tenant}/v2.0}
          audiences:
          - ${AZURE_AUDIENCE_ID:00000000-0000-0000-0000-000000000000}
          - ${AZURE_AUDIENCE_ID_URI:api://${AZURE_AUDIENCE_ID}}
          tenant: ${AZURE_TENANT_ID:00000000-0000-0000-0000-000000000000}

app:
  timezone: "Europe/London"

azure:
  application-insights:
    instrumentation-key: ${AppInsightsInstrumentationKey:00000000-0000-0000-0000-000000000000}


appreg:
  bulk-import:
    page-size: ${BULK_IMPORT_PAGE_SIZE:250}
    write-audit-mode: ${BULK_IMPORT_WRITE_AUDIT_MODE:BULK}
  bulk-action-preview:
    global-limit: 2000
  audit:
    diff:
      enable-complex-diff: true
  csds:
    ingress:
      base-url: ${CSDS_BASE_URL:http://noop}
      access-keys:
      - ${CSDS_KEY_1:missing_1}
      - ${CSDS_KEY_2:missing_2}
      access-key-header: Api-Key
      lease-duration: PT5M
      connect-timeout: PT10S
      read-timeout: PT30S
      page-size: 100
      processors:
        application-codes:
          enabled: false
          table-name: application_codes_staging
          primary-key: ac_id
          source-entity-name: ApplicationCode
          parameters: ?%24f=PublishingStatus='Active'&%24expr=Updator&%24orderBy=ApplicationCodeID
#          mock: csds/application_codes.json
#          reporting-dir: ${CSDS_APPLICATION_CODES_REPORTING_DIR:}
        resolution-codes:
          enabled: false
          table-name: resolution_codes_staging
          primary-key: rc_id
          source-entity-name: ResolutionCode
          parameters: ?%24f=PublishingStatus='Active'&%24expr=Updator&%24orderBy=ResolutionCodeID
#          mock: csds/resolution_codes.json
#          reporting-dir: ${CSDS_RESOLUTION_CODES_REPORTING_DIR:}
        fee:
          enabled: false
          table-name: fee_staging
          primary-key: fee_id
          source-entity-name: CivilFee
          parameters: ?%24f=AuthoringStatus='Published'&%24expr=Updator&%24orderBy=CivilFeeID
#          mock: csds/fee.json
#          reporting-dir: ${CSDS_FEE_REPORTING_DIR:}
        standard-applicants:
          enabled: false
          table-name: standard_applicants_staging
          primary-key: sa_id
          source-entity-name: DA_GetStandardApplicant
          parameters: ?%24f=PublishingStatus='Active'&%24f=CurrentRecordIndicator='true'&%24expr=Updator&%24orderBy=ApplicantID
#          mock: csds/standard_applicants.json
#          reporting-dir: ${CSDS_STANDARD_APPLICANTS_REPORTING_DIR:}
  job:
    page-size: 10
  report:
    page-size: 500
