spring:
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:${wiremock.server.port}/discovery/v2.0/keys

logging:
  level:
    root: INFO
    WireMock: WARN
    org.eclipse.jetty: WARN
    org.springframework: WARN
    org.springframework.security: WARN
    org.wiremock: WARN
    uk.gov.hmcts.appregister.audit.listener.DataAuditLogger: DEBUG
    uk.gov.hmcts.appregister.audit.listener.diff.ReflectiveAuditor: DEBUG
appreg:
  audit:
    diff:
      enable-complex-diff: true
  job:
    page-size: 2
