databaseType = "PostgreSql"
id = "85f505ac-5c52-431a-a644-b4834590d060"
name = "flyway_data_migration_validation"

[flyway]
locations = [ "filesystem:migrations" ]
mixed = true
outOfOrder = true
schemaModelLocation = "schema-model"
validateMigrationNaming = true

  [flyway.check]
  majorTolerance = 0

[flywayDesktop]
developmentEnvironment = "development"
shadowEnvironment = "shadow"
enableMigrations = false

[redgateCompare]
filterFile = "filter.rgf"

[redgateCompare.postgresql.options.behavior]
detectRenames = "identical-only"

[redgateCompare.postgresql.options.ignores]
ignoreNewlinesInTextObjects = "off"

[environments.staging]
url = "jdbc:postgresql://appreg-stg.postgres.database.azure.com/appreg-db"
schemas = [ "csds" ]
displayName = "staging"

[environments.localhost]
url = "jdbc:postgresql://127.0.0.1:5432/appreg-db"
schemas = [ "csds" ]
displayName = "localhost"
