type: object
description: Represents the result of an Application List Entries move operation.
required:
  - overallStatus
  - movedCount

properties:

  overallStatus:
    $ref: './application-list-entries-move-status.yaml'

  movedCount:
    type: integer
    format: int32
    minimum: 0
    description: Total number of Application List Entries moved.
    example: 12
